### PR TITLE
Room schedule view

### PR DESCRIPTION
**Pull request by aswenson99**

### CODE REVIEW

**Comment by aswenson99** [comment]
image

**Comment by aswenson99** [comment]
image
image

**Comment by aswenson99** [comment]
image

**Comment by meganbailey** [comment]
Can we change the print button to a button with a print icon (like the add nurse button) 
image

And then the add appointment to have similar styling (rounded navy) with white text "Add Appointment"

**Comment by meganbailey** [comment]
For add appointment modal, can we default the selection of the dropdowns to 'Select'?

**Pull request merged**
